mod config;
mod error;
mod metadata;
mod resource;
mod task;

pub use config::*;
pub use error::*;
pub use metadata::*;
pub use resource::*;
pub use task::*;

#[derive(Clone, Copy, Debug, serde::Deserialize, PartialEq, Eq, serde::Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub enum ExternalDestinationDto {
    Repository,
    Issues,
    CurrentRelease,
    BilibiliProfile,
    BilibiliFeedback,
}

#[derive(Clone, Debug, serde::Deserialize, PartialEq, Eq, serde::Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub struct ExternalDestinationRequestDto {
    pub destination: ExternalDestinationDto,
}

#[cfg(test)]
#[must_use]
pub fn generated_types() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        BootstrapDto::decl(&config),
        PublicConfigDto::decl(&config),
        RenderOptionsDto::decl(&config),
        BackgroundRatioDto::decl(&config),
        TemplateFieldDto::decl(&config),
        TemplateDto::decl(&config),
        FontSpecDto::decl(&config),
        CaseConversionDto::decl(&config),
        FieldContentKindDto::decl(&config),
        TemplateKindDto::decl(&config),
        VerticalAlignDto::decl(&config),
        ResourceKindDto::decl(&config),
        ResourceDescriptorDto::decl(&config),
        TaskStateDto::decl(&config),
        CancellationReasonDto::decl(&config),
        TaskDescriptorDto::decl(&config),
        TaskStatusEventDto::decl(&config),
        MetadataDto::decl(&config),
        CommandErrorDto::decl(&config),
        UpdateConfigRequestDto::decl(&config),
        ResourceIdRequestDto::decl(&config),
        RegisterFontRequestDto::decl(&config),
        TaskIdRequestDto::decl(&config),
        TaskIdsRequestDto::decl(&config),
        ExternalDestinationDto::decl(&config),
        ExternalDestinationRequestDto::decl(&config),
    ];
    format!(
        "// Generated by yiyin-desktop. Do not edit.\n\n{}\n",
        declarations
            .into_iter()
            .map(|declaration| format!("export {declaration}"))
            .collect::<Vec<_>>()
            .join("\n\n")
    )
}
