// Generated by yiyin-desktop. Do not edit.

export type BootstrapDto = { config: PublicConfigDto, constraints: { [key in NumericOptionDto]?: NumericConstraintDto }, resources: Array<ResourceDescriptorDto>, tasks: Array<TaskDescriptorDto>, warnings: Array<string>, };

export type NumericConstraintDto = { minimum: number, maximum: number, decimals: number, };

export type NumericOptionDto = "mainImageWidth" | "textMargin" | "miniTopBottomMargin" | "radius" | "shadow" | "quality" | "backgroundBlur";

export type PublicConfigDto = { version: string, options: RenderOptionsDto, templateFields: Array<TemplateFieldDto>, customTemplateFields: Array<TemplateFieldDto>, templates: Array<TemplateDto>, };

export type RenderOptionsDto = { quickOutput: boolean, landscape: boolean, solidBackground: boolean, solidColor: string, radius: number, radiusVisible: boolean, shadow: number, shadowVisible: boolean, backgroundRatioVisible: boolean, backgroundRatio: BackgroundRatioDto, font: string, mainImageWidth: number, textMargin: number, quality: number, miniTopBottomMargin: number, backgroundBlur: number, previewVisible: boolean, };

export type BackgroundRatioDto = { width: number, height: number, };

export type TemplateFieldDto = { key: string, name: string, visible: boolean, useCustomValue: boolean, forceCustomValue: boolean, customValue: string, contentKind: FieldContentKindDto, darkImageId: string | null, lightImageId: string | null, fontOverride: FontSpecDto | null, };

export type TemplateDto = { key: string, name: string, format: string, enabled: boolean, kind: TemplateKindDto, height: number | null, font: FontSpecDto, verticalAlign: VerticalAlignDto, };

export type FontSpecDto = { family: string, size: number, bold: boolean, italic: boolean, caseConversion: CaseConversionDto, color: string, };

export type CaseConversionDto = "default" | "lowercase" | "uppercase";

export type FieldContentKindDto = "text" | "image";

export type TemplateKindDto = "system" | "custom";

export type VerticalAlignDto = "center" | "baseline";

export type ResourceKindDto = "bundledAsset" | "font" | "overlay" | "input" | "preview" | "output";

export type ResourceDescriptorDto = { id: string, kind: ResourceKindDto, displayName: string, url: string, };

export type TaskStateDto = "registered" | "queued" | "running" | "completed" | "failed" | "cancelled";

export type CancellationReasonDto = "user" | "previewSuperseded" | "cleared" | "shutdown";

export type TaskDescriptorDto = { id: string, displayName: string, state: TaskStateDto, progress: number, preview: boolean, resource: ResourceDescriptorDto | null, };

export type TaskStatusEventDto = { taskId: string, state: TaskStateDto, progress: number, preview: boolean, cancellationReason: CancellationReasonDto | null, };

export type MetadataDto = { fields: { [key in string]: string }, };

export type CommandErrorDto = { code: string, message: string, };

export type UpdateConfigRequestDto = { config: PublicConfigDto, };

export type ResourceIdRequestDto = { id: string, };

export type RegisterFontRequestDto = { name: string, };

export type TaskIdRequestDto = { id: string, };

export type TaskIdsRequestDto = { ids: Array<string>, };

export type ExternalDestinationDto = "repository" | "issues" | "currentRelease" | "bilibiliProfile" | "bilibiliFeedback";

export type ExternalDestinationRequestDto = { destination: ExternalDestinationDto, };
